spring:
  application:
    name: ssaktium
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME} # 이메일을 전송할 주체의 이메일 주소
    password: ${APP_PASSWORD} # 해당 계정으로 발급받은 App password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  profiles:
    active: local

#data:
#  redis:
#    cluster:
#      nodes:
#        - localhost:7000
#        - localhost:7001
#        - localhost:7002

toss:
  payment:
    secret:
      key: ${TOSS_SECRET_KEY}


management:
  endpoints:
    web:
      exposure:
        include: health,info  # 필요한 엔드포인트 노출 (health와 info를 포함)
  endpoint:
    health:
      show-details: always  # health 상태에 대한 세부 정보를 항상 표시
      probes:
        enabled: true       # 기본적인 시스템 상태(디스크, 메모리 등) 활성화
      details:
        enabled-by-default: true
  health:
    diskspace:
      enabled: true         # 디스크 상태 정보 활성화
      threshold: 100MB      # 디스크 여유 공간이 100MB 이하일 때 경고
    db:
      enabled: true         # 데이터베이스 상태 정보 활성화
    memory:
      enabled: true         # 메모리 상태 정보 활성화

