server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset : UTF-8
      enabled: true
      force: true

spring:
  web:
    resources:
      static-locations: classpath:/static/
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME_DEV}
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD_DEV}
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: "http://13.124.138.199:8080/ssaktium/signin/kakao"
            authorization-grant-type: authorization_code
            scope: profile_nickname, account_email, birthyear
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://13.124.138.199:8080/ssaktium/signin/google"
            authorization-grant-type: authorization_code
            scope: email, profile, https://www.googleapis.com/auth/user.birthday.read
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            redirect-uri: "http://13.124.138.199:8080/ssaktium/signin-naver"
            authorization-grant-type: authorization_code
            scope: name, email, birthyear

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response.id

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  elasticsearch:
    uris: http://172.31.4.160:9200
#    username: ${ES_USERNAME}
#    password: ${ES_PASSWORD}

  data:
    redis:
      host: 172.31.10.161
      port: 6379

app:
  redirectUri: "http://13.124.138.199:8080/ssaktium/signin/"
  kafka-brokers : "172.31.40.10:19092, 172.31.40.10:19093, 172.31.40.10:19094"

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false